import type { Pillar, PillarId } from "./types";

export const PILLARS: Pillar[] = [
  {
    id: "arah",
    roman: "I",
    name: "Arah",
    short: "Navigasi",
    job: "Menjawab ke mana kita pergi, mengapa itu, dan apa yang tidak kita kerjakan.",
    why: "Tanpa arah yang tajam, organisasi yang cerdas pun sibuk ke segala penjuru. CEO adalah satu-satunya orang yang wajib menjaga narasi tunggal: diagnosis realitas, pilihan yang sadar, dan taruhan yang bisa diuji.",
    promise: "Setiap orang di perusahaan bisa menjelaskan strategi dalam satu kalimat, dan tahu tiga hal yang sengaja tidak dikerjakan.",
    questions: [
      { id: "arah-1", text: "Saya bisa menjelaskan strategi perusahaan dalam 30 detik tanpa slide." },
      { id: "arah-2", text: "Tim senior punya gambaran yang sama tentang 3 prioritas tahun ini." },
      { id: "arah-3", text: "Kita secara sadar menulis apa yang tidak kita kerjakan." },
      { id: "arah-4", text: "Saya merevisi strategi dari sinyal pasar, bukan dari ego atau inersia." },
    ],
    practices: [
      { cadence: "mingguan", title: "Narasi satu halaman", detail: "Tulis ulang diagnosis, pilihan, dan taruhan. Jika tidak muat satu halaman, itu belum strategi." },
      { cadence: "bulanan", title: "Uji dengan 5 pelanggan", detail: "Baca strategi ke 5 pelanggan atau pengguna. Catat apa yang mereka anggap tidak relevan." },
      { cadence: "kuartalan", title: "Pilihan yang dibunuh", detail: "Setiap kuartal, bunuh atau tunda minimal satu inisiatif yang terdengar bagus tapi tidak masuk taruhan inti." },
    ],
    antipatterns: [
      "Visi yang puitis tanpa pilihan yang menyakitkan.",
      "Strategi = daftar proyek dari setiap fungsi.",
      "Berganti arah setiap kali ada kompetitor baru.",
      "Hanya CEO yang mengerti 'mengapa' — sisanya menunggu perintah.",
    ],
    teamQuestions: [
      "Jika kita hanya boleh memenangkan satu pertempuran 18 bulan ke depan, pertempuran mana?",
      "Apa asumsi paling mahal yang belum kita uji?",
      "Ke mana kompetitor ingin kita tersesat?",
    ],
    weeklyMove: "Tulis strategi satu halaman. Bagikan ke tim senior. Minta mereka menandai kalimat yang tidak mereka yakini.",
    firstMove: "Tulis dalam 8 baris: siapa pelanggan, masalah apa, mengapa kita, mengapa sekarang, taruhan utama, yang tidak kita lakukan.",
  },
  {
    id: "orang",
    roman: "II",
    name: "Orang",
    short: "Kru",
    job: "Membangun kepadatan bakat di kursi yang tepat, lalu menahan diri untuk tidak menjadi pahlawan.",
    why: "Output CEO adalah output organisasi. Satu orang yang salah di kursi kunci merusak lebih banyak daripada 10 keputusan produk yang sedang-sedang saja. CEO yang hebat obsesif pada siapa, bukan hanya apa.",
    promise: "Setiap kursi kunci punya pemilik yang jelas, standar yang tertulis, dan keputusan keep / coach / move yang tidak ditunda.",
    questions: [
      { id: "orang-1", text: "Saya punya kriteria tertulis (scorecard) untuk setiap kursi kunci." },
      { id: "orang-2", text: "Saya tidak menunda keputusan orang yang sudah jelas tidak cocok." },
      { id: "orang-3", text: "1:1 dengan laporan langsung terjadi andal, bukan sisa waktu." },
      { id: "orang-4", text: "Tim senior saling percaya cukup untuk berkonflik tentang substansi." },
    ],
    practices: [
      { cadence: "mingguan", title: "1:1 yang dimiliki mereka", detail: "Agenda milik laporan langsung. Anda mendengar, menantang, dan membuka jalan — bukan briefing status." },
      { cadence: "bulanan", title: "Peta bakat", detail: "Plot kinerja × potensi. Tandai siapa yang harus dinaikkan, dilatih, atau dipindah dalam 90 hari." },
      { cadence: "kuartalan", title: "Kursi kunci", detail: "Untuk 5–8 kursi paling mahal: apakah orang ini akan saya rekrut ulang hari ini? Jika tidak, apa rencananya." },
    ],
    antipatterns: [
      "Merekrut dari 'kesan pintar' tanpa scorecard.",
      "Menahan underperformer karena loyalitas atau rasa bersalah.",
      "CEO menjadi manajer cadangan untuk setiap fungsi.",
      "1:1 yang isinya update status yang sudah ada di dashboard.",
    ],
    teamQuestions: [
      "Jika orang ini resign besok, saya lega atau panik?",
      "Kursi mana yang jika diisi A-player akan mengubah perusahaan dalam 6 bulan?",
      "Apa yang saya toleransi di tim senior yang tidak akan saya toleransi di level staf?",
    ],
    weeklyMove: "Jadwalkan 1:1 minggu ini dengan setiap laporan langsung. Minta mereka membawa 3 topik, bukan laporan.",
    firstMove: "Tulis 5 kursi kunci dan nama penghuninya. Tandai hijau / kuning / merah. Merah wajib punya rencana 90 hari.",
  },
  {
    id: "eksekusi",
    roman: "III",
    name: "Eksekusi",
    short: "Laku",
    job: "Mengubah arah menjadi ritme: prioritas sedikit, pemilik tunggal, dan tinjauan yang tidak bisa dihindari.",
    why: "Strategi tanpa eksekusi adalah opini. Eksekusi tanpa strategi adalah sibuk. CEO merancang sistem agar pekerjaan penting terjadi meski ia tidak ada di ruangan.",
    promise: "Paling banyak lima prioritas perusahaan, masing-masing satu pemilik, ditinjau setiap minggu tanpa drama.",
    questions: [
      { id: "eksekusi-1", text: "Perusahaan punya paling banyak 5 prioritas yang semua orang hafal." },
      { id: "eksekusi-2", text: "Setiap prioritas punya satu nama pemilik, bukan 'tim'." },
      { id: "eksekusi-3", text: "Rapat kepemimpinan mingguan meninjau angka dan hambatan, bukan slide." },
      { id: "eksekusi-4", text: "Saya tahu apa yang macet minggu ini tanpa harus bertanya ke lima orang." },
    ],
    practices: [
      { cadence: "harian", title: "Satu taruhan hari ini", detail: "Tulis 1 pekerjaan yang hanya bisa diselesaikan CEO. Selesaikan sebelum inbox." },
      { cadence: "mingguan", title: "Rapat staf 60–90 menit", detail: "Scorecard, prioritas, hambatan, keputusan. Tidak ada status theater." },
      { cadence: "kuartalan", title: "OKR atau setara", detail: "3–5 objektif. Key result yang terukur. Sisanya adalah pekerjaan biasa, bukan prioritas." },
    ],
    antipatterns: [
      "12 prioritas = 0 prioritas.",
      "Rapat yang menghasilkan rapat lanjutan.",
      "CEO yang menjadi bottleneck persetujuan.",
      "Mengukur kesibukan (jam, tiket) alih-alih hasil.",
    ],
    teamQuestions: [
      "Jika kita hanya menyelesaikan satu hal bulan ini, apa itu?",
      "Apa yang kita kerjakan yang tidak mengubah angka mana pun?",
      "Di mana saya, sebagai CEO, justru memperlambat?",
    ],
    weeklyMove: "Potong daftar prioritas sampai maksimal lima. Sisanya masuk 'parkir' dengan tanggal tinjauan.",
    firstMove: "Tulis 3 hasil yang harus benar dalam 90 hari. Tempel di rapat staf.",
  },
  {
    id: "keputusan",
    roman: "IV",
    name: "Keputusan",
    short: "Putusan",
    job: "Membuat keputusan yang tepat secepat yang aman, dan mendelegasikan sisanya dengan konteks.",
    why: "Kecepatan keputusan adalah kecepatan perusahaan. CEO yang menahan keputusan dua-arah di mejanya merampok momentum. CEO yang ceroboh pada keputusan satu-arah merampok masa depan.",
    promise: "Setiap keputusan mahal punya jenis (satu/dua arah), pemilik, tenggat, dan tanggal tinjauan.",
    questions: [
      { id: "keputusan-1", text: "Saya membedakan keputusan satu-arah (mahal dibalik) dan dua-arah (bisa diuji)." },
      { id: "keputusan-2", text: "Hak keputusan di tim senior jelas: siapa merekomendasikan, siapa memutuskan." },
      { id: "keputusan-3", text: "Keputusan besar punya pre-mortem tertulis sebelum dijalankan." },
      { id: "keputusan-4", text: "Saya tidak membuka ulang keputusan yang sudah ditutup tanpa data baru." },
    ],
    practices: [
      { cadence: "harian", title: "Eskalasi 48 jam", detail: "Keputusan yang menunggu Anda lebih dari 48 jam harus diputuskan, didelegasikan, atau dijadwalkan." },
      { cadence: "mingguan", title: "Log keputusan", detail: "Catat keputusan material: konteks, opsi, putusan, pemilik, kapan ditinjau." },
      { cadence: "bulanan", title: "Tinjau yang salah", detail: "Ambil 1 keputusan buruk. Bedakan: prosesnya salah, atau hasilnya sial? Perbaiki proses." },
    ],
    antipatterns: [
      "Konsensus sebagai pelindung dari tanggung jawab.",
      "Keputusan lewat chat yang tidak terdokumentasi.",
      "Membuka ulang keputusan karena orang paling vokal belum puas.",
      "Mendelegasikan tanpa konteks, lalu marah karena hasilnya beda.",
    ],
    teamQuestions: [
      "Ini pintu satu arah atau dua arah?",
      "Keputusan apa yang hanya boleh saya buat — dan apa yang tidak boleh?",
      "Kalau ini gagal 12 bulan lagi, apa yang akan kita sesali tidak ditanyakan hari ini?",
    ],
    weeklyMove: "Ambil satu keputusan yang tertahan. Tandai jenisnya. Putuskan atau delegasikan hari ini.",
    firstMove: "Buat aturan: dua-arah diputuskan di level terendah yang punya konteks. Satu-arah naik ke CEO dengan memo 1 halaman.",
  },
  {
    id: "modal",
    roman: "V",
    name: "Modal",
    short: "Oksigen",
    job: "Menjaga perusahaan tetap hidup, lalu mengalokasikan uang, waktu, dan perhatian ke taruhan dengan imbal hasil tertinggi.",
    why: "Kas adalah oksigen. Alokasi modal adalah pekerjaan CEO yang tidak bisa didelegasikan sepenuhnya: ke mana uang, orang, dan fokus pergi adalah strategi yang sebenarnya.",
    promise: "Saya bisa menyebutkan runway, unit economics, dan 3 tempat uang paling tidak produktif tanpa membuka spreadsheet.",
    questions: [
      { id: "modal-1", text: "Saya tahu runway dan titik default tanpa menunggu laporan keuangan." },
      { id: "modal-2", text: "Unit economics inti (kontribusi, CAC, payback, atau margin kotor) saya hafal." },
      { id: "modal-3", text: "Kita punya ritme tinjauan kas dan P&L yang tidak bisa dilewatkan." },
      { id: "modal-4", text: "Saya memotong atau menunda pengeluaran yang tidak mendukung taruhan inti." },
    ],
    practices: [
      { cadence: "mingguan", title: "Kas 13 minggu", detail: "Lihat posisi kas, koleksi, dan pengeluaran besar. Kejutan kas adalah kegagalan proses, bukan nasib." },
      { cadence: "bulanan", title: "Alokasi vs strategi", detail: "Cocokkan spend dengan 5 prioritas. Apa yang dibiayai tapi tidak prioritas?" },
      { cadence: "kuartalan", title: "Satu taruhan besar", detail: "Putuskan satu alokasi yang tidak sepele: hire, capex, channel, atau kill a line." },
    ],
    antipatterns: [
      "CEO yang 'tidak suka angka' dan menyerahkan seluruhnya ke CFO tanpa pertanyaan.",
      "Tumbuh sekarang, untung nanti — tanpa model kapan 'nanti'.",
      "Vanity metrics yang menyembunyikan unit economics rusak.",
      "Merekrut di depan pendapatan secara kronis.",
    ],
    teamQuestions: [
      "Jika kas memburuk 30%, apa yang kita hentikan minggu ini?",
      "Satu dollar berikutnya sebaiknya ke mana — dan mengapa bukan ke tempat lain?",
      "Metrik mana yang jika hijau tapi pelanggan menderita, kita sedang menipu diri?",
    ],
    weeklyMove: "Tulis di kertas: runway, burn, margin kotor atau kontribusi, dan satu pengeluaran yang akan Anda bunuh.",
    firstMove: "Minta laporan kas 13 minggu. Jika belum ada, itu prioritas minggu ini — di atas fitur baru.",
  },
  {
    id: "produk",
    roman: "VI",
    name: "Produk",
    short: "Nilai",
    job: "Memastikan perusahaan menciptakan nilai yang orang bayar, ceritakan, dan tidak rela tinggalkan.",
    why: "Semua fungsi lain adalah turunan dari nilai di tangan pelanggan. CEO yang jauh dari pelanggan akan memimpin perusahaan yang elegan dan tidak relevan.",
    promise: "Saya berbicara dengan pelanggan setiap minggu, dan peta masalah mereka lebih akurat daripada peta roadmap internal.",
    questions: [
      { id: "produk-1", text: "Saya berbicara dengan pelanggan atau pengguna setiap minggu." },
      { id: "produk-2", text: "Kita punya bukti (bukan opini) mengapa orang membeli dan mengapa orang pergi." },
      { id: "produk-3", text: "Roadmap adalah taruhan terurut, bukan daftar keinginan pemangku kepentingan." },
      { id: "produk-4", text: "Kualitas dan janji merek tidak dirusak demi rilis yang terburu-buru." },
    ],
    practices: [
      { cadence: "mingguan", title: "Kontak pelanggan", detail: "Minimal 3 percakapan nyata: call, kunjungan, atau duduk di support. Catat kata-kata mereka, bukan ringkasan Anda." },
      { cadence: "bulanan", title: "Mengapa beli / mengapa pergi", detail: "Tinjau win-loss atau churn. Satu pola yang berulang menjadi agenda produk, bukan catatan kaki." },
      { cadence: "kuartalan", title: "Janji merek", detail: "Apa yang kita janjikan secara implisit? Di mana kita gagal menepatinya?" },
    ],
    antipatterns: [
      "Roadmap yang diisi sales-led one-off.",
      "CEO yang terakhir kali memakai produknya sendiri 8 bulan lalu.",
      "Mengukur output tim produk (fitur) bukan outcome pelanggan.",
      "Menyembunyikan kualitas buruk di belakang growth hacking.",
    ],
    teamQuestions: [
      "Masalah pelanggan mana yang jika diselesaikan membuat sisanya menjadi sepele?",
      "Apa yang pelanggan sewa dari kita — dan apa substitusinya?",
      "Jika kita hilang 6 bulan, siapa yang merindukan kita?",
    ],
    weeklyMove: "Jadwalkan 3 percakapan pelanggan minggu ini. Jangan delegasikan semuanya.",
    firstMove: "Pakai produk Anda sendiri end-to-end hari ini. Catat 10 gesekan. Kirim ke kepala produk tanpa solusi — hanya gesekan.",
  },
  {
    id: "budaya",
    roman: "VII",
    name: "Budaya",
    short: "Iklim",
    job: "Menjadikan nilai sebagai mekanisme, bukan poster: apa yang dihargai, apa yang ditoleransi, bagaimana keputusan benar-benar dibuat.",
    why: "Budaya adalah apa yang terjadi ketika Anda tidak ada. Itu terbentuk dari siapa yang dipromosikan, siapa yang ditoleransi, dan bagaimana rapat dijalankan. CEO adalah kurator iklim, sadar atau tidak.",
    promise: "Nilai perusahaan terlihat di keputusan orang, rapat, dan umpan balik — bukan di dinding resepsionis.",
    questions: [
      { id: "budaya-1", text: "Nilai perusahaan dipakai saat merekrut, mempromosikan, dan memberhentikan." },
      { id: "budaya-2", text: "Konflik substansi di tim senior diundang, bukan dihindari." },
      { id: "budaya-3", text: "Informasi buruk naik cepat ke saya, bukan disaring sampai indah." },
      { id: "budaya-4", text: "Saya mencontohkan standar yang saya minta — kalender, ketepatan, cara bicara." },
    ],
    practices: [
      { cadence: "mingguan", title: "Cerita, bukan slogan", detail: "Di rapat staf, ceritakan satu perilaku yang ingin Anda lihat lebih banyak. Budaya menyebar lewat cerita." },
      { cadence: "bulanan", title: "Audit toleransi", detail: "Perilaku apa yang Anda biarkan meski menggerogoti standar? Satu toleransi membatalkan sepuluh pidato." },
      { cadence: "kuartalan", title: "Rapat sebagai budaya", detail: "Rekam (secara metaforis) bagaimana rapat berjalan: terlambat, interrupt, undangan yang tidak perlu. Perbaiki mekaniknya." },
    ],
    antipatterns: [
      "Nilai yang tidak bisa dipakai untuk menolak kandidat.",
      "CEO yang kasar ke staf, ramah ke board.",
      "Politik istana: akses ke CEO lebih berharga daripada kinerja.",
      "Keselamatan psikologis yang disalahartikan sebagai menghindari konflik.",
    ],
    teamQuestions: [
      "Perilaku apa yang kita promosikan secara tidak sengaja?",
      "Siapa yang berani membawa kabar buruk ke saya — dan siapa yang tidak berani?",
      "Jika orang baru meniru rapat kita, apa yang akan mereka pelajari tentang kekuasaan?",
    ],
    weeklyMove: "Pilih satu nilai. Tulis keputusan konkret minggu ini yang hanya masuk akal karena nilai itu.",
    firstMove: "Tulis 3 perilaku yang tidak boleh ada di tim senior. Bagikan. Minta mereka menilai Anda pertama kali.",
  },
  {
    id: "diri",
    roman: "VIII",
    name: "Diri",
    short: "Kemudi",
    job: "Menjaga kejelasan berpikir, energi, dan kalender — karena perusahaan tidak bisa lebih sehat dari CEO-nya.",
    why: "CEO yang kelelahan membuat keputusan pendek. Kalender adalah strategi yang terlihat. Jika minggu Anda penuh rapat reaktif, perusahaan akan menjadi reaktif.",
    promise: "Ada waktu berpikir yang dilindungi, tidur yang cukup, dan satu orang yang berhak menantang saya secara pribadi.",
    questions: [
      { id: "diri-1", text: "Kalender saya mencerminkan prioritas, bukan permintaan orang lain." },
      { id: "diri-2", text: "Saya punya blok berpikir yang dilindungi setiap minggu." },
      { id: "diri-3", text: "Tidur, tubuh, dan hubungan dekat tidak menjadi sisa dari pekerjaan." },
      { id: "diri-4", text: "Saya punya penasihat atau peer yang berhak menantang saya tanpa politik." },
    ],
    practices: [
      { cadence: "harian", title: "Pertama yang penting", detail: "90 menit pertama: pekerjaan CEO yang berat. Inbox belakangan. Telepon tidak memimpin pagi Anda." },
      { cadence: "mingguan", title: "Tinjauan CEO", detail: "60 menit: apa yang hanya saya yang bisa kerjakan, apa yang harus saya hentikan, siapa yang perlu saya angkat." },
      { cadence: "bulanan", title: "Audit kalender", detail: "Warna-warnai minggu lalu: berpikir, orang, keputusan, firefighting, theater. Target firefighting < 20%." },
    ],
    antipatterns: [
      "Bangga pada inbox nol dan kalender penuh.",
      "Tidak ada peer — hanya bawahan dan board.",
      "Menyelesaikan kelelahan dengan lebih banyak kopi dan lebih sedikit jujur.",
      "Menjadi bottleneck karena merasa dibutuhkan.",
    ],
    teamQuestions: [
      "Jika saya cuti 2 minggu, apa yang rusak — dan mengapa itu masih bergantung pada saya?",
      "Pekerjaan apa yang saya kerjakan karena nyaman, bukan karena hanya CEO yang bisa?",
      "Siapa yang boleh bilang 'Anda salah' tanpa takut?",
    ],
    weeklyMove: "Blok 3 jam berpikir di kalender minggu depan. Perlakukan seperti rapat dengan investor terpenting: diri Anda.",
    firstMove: "Audit kalender 7 hari ke belakang. Hapus atau delegasikan 20% yang tidak membutuhkan CEO.",
  },
];

export function pillarById(id: PillarId) {
  const found = PILLARS.find((p) => p.id === id);
  if (!found) throw new Error(`Unknown pillar: ${id}`);
  return found;
}

export const SCORE_LABELS = ["", "Lemah", "Berkembang", "Cukup", "Kuat", "Unggul"] as const;
