/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDiagnostikRouteImport } from './routes/_app.diagnostik'
import { Route as AppJurnalRouteImport } from './routes/_app.jurnal'
import { Route as AppKeputusanRouteImport } from './routes/_app.keputusan'
import { Route as AppPanduanRouteImport } from './routes/_app.panduan'
import { Route as AppPlaybookRouteImport } from './routes/_app.playbook'
import { Route as AppPrioritasRouteImport } from './routes/_app.prioritas'
import { Route as AppRencanaRouteImport } from './routes/_app.rencana'
import { Route as AppRitmeRouteImport } from './routes/_app.ritme'
import { Route as AppScorecardRouteImport } from './routes/_app.scorecard'
import { Route as AppTimRouteImport } from './routes/_app.tim'
import { Route as AppPilarIndexRouteImport } from './routes/_app.pilar.index'
import { Route as AppPilarIdRouteImport } from './routes/_app.pilar.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnostikRoute = AppDiagnostikRouteImport.update({
  id: '/diagnostik',
  path: '/diagnostik',
  getParentRoute: () => AppRoute,
} as any)
const AppJurnalRoute = AppJurnalRouteImport.update({
  id: '/jurnal',
  path: '/jurnal',
  getParentRoute: () => AppRoute,
} as any)
const AppKeputusanRoute = AppKeputusanRouteImport.update({
  id: '/keputusan',
  path: '/keputusan',
  getParentRoute: () => AppRoute,
} as any)
const AppPanduanRoute = AppPanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybookRoute = AppPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AppRoute,
} as any)
const AppPrioritasRoute = AppPrioritasRouteImport.update({
  id: '/prioritas',
  path: '/prioritas',
  getParentRoute: () => AppRoute,
} as any)
const AppRencanaRoute = AppRencanaRouteImport.update({
  id: '/rencana',
  path: '/rencana',
  getParentRoute: () => AppRoute,
} as any)
const AppRitmeRoute = AppRitmeRouteImport.update({
  id: '/ritme',
  path: '/ritme',
  getParentRoute: () => AppRoute,
} as any)
const AppScorecardRoute = AppScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => AppRoute,
} as any)
const AppTimRoute = AppTimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => AppRoute,
} as any)
const AppPilarIndexRoute = AppPilarIndexRouteImport.update({
  id: '/pilar/',
  path: '/pilar/',
  getParentRoute: () => AppRoute,
} as any)
const AppPilarIdRoute = AppPilarIdRouteImport.update({
  id: '/pilar/$id',
  path: '/pilar/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/diagnostik': typeof AppDiagnostikRoute
  '/jurnal': typeof AppJurnalRoute
  '/keputusan': typeof AppKeputusanRoute
  '/panduan': typeof AppPanduanRoute
  '/playbook': typeof AppPlaybookRoute
  '/prioritas': typeof AppPrioritasRoute
  '/rencana': typeof AppRencanaRoute
  '/ritme': typeof AppRitmeRoute
  '/scorecard': typeof AppScorecardRoute
  '/tim': typeof AppTimRoute
  '/pilar/$id': typeof AppPilarIdRoute
  '/pilar/': typeof AppPilarIndexRoute
}
export interface FileRoutesByTo {
  '/diagnostik': typeof AppDiagnostikRoute
  '/jurnal': typeof AppJurnalRoute
  '/keputusan': typeof AppKeputusanRoute
  '/panduan': typeof AppPanduanRoute
  '/playbook': typeof AppPlaybookRoute
  '/prioritas': typeof AppPrioritasRoute
  '/rencana': typeof AppRencanaRoute
  '/ritme': typeof AppRitmeRoute
  '/scorecard': typeof AppScorecardRoute
  '/tim': typeof AppTimRoute
  '/': typeof AppIndexRoute
  '/pilar/$id': typeof AppPilarIdRoute
  '/pilar': typeof AppPilarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/diagnostik': typeof AppDiagnostikRoute
  '/_app/jurnal': typeof AppJurnalRoute
  '/_app/keputusan': typeof AppKeputusanRoute
  '/_app/panduan': typeof AppPanduanRoute
  '/_app/playbook': typeof AppPlaybookRoute
  '/_app/prioritas': typeof AppPrioritasRoute
  '/_app/rencana': typeof AppRencanaRoute
  '/_app/ritme': typeof AppRitmeRoute
  '/_app/scorecard': typeof AppScorecardRoute
  '/_app/tim': typeof AppTimRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pilar/$id': typeof AppPilarIdRoute
  '/_app/pilar/': typeof AppPilarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostik'
    | '/jurnal'
    | '/keputusan'
    | '/panduan'
    | '/playbook'
    | '/prioritas'
    | '/rencana'
    | '/ritme'
    | '/scorecard'
    | '/tim'
    | '/pilar/$id'
    | '/pilar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/diagnostik'
    | '/jurnal'
    | '/keputusan'
    | '/panduan'
    | '/playbook'
    | '/prioritas'
    | '/rencana'
    | '/ritme'
    | '/scorecard'
    | '/tim'
    | '/'
    | '/pilar/$id'
    | '/pilar'
  id:
    | '__root__'
    | '/_app'
    | '/_app/diagnostik'
    | '/_app/jurnal'
    | '/_app/keputusan'
    | '/_app/panduan'
    | '/_app/playbook'
    | '/_app/prioritas'
    | '/_app/rencana'
    | '/_app/ritme'
    | '/_app/scorecard'
    | '/_app/tim'
    | '/_app/'
    | '/_app/pilar/$id'
    | '/_app/pilar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostik': {
      id: '/_app/diagnostik'
      path: '/diagnostik'
      fullPath: '/diagnostik'
      preLoaderRoute: typeof AppDiagnostikRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jurnal': {
      id: '/_app/jurnal'
      path: '/jurnal'
      fullPath: '/jurnal'
      preLoaderRoute: typeof AppJurnalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keputusan': {
      id: '/_app/keputusan'
      path: '/keputusan'
      fullPath: '/keputusan'
      preLoaderRoute: typeof AppKeputusanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panduan': {
      id: '/_app/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof AppPanduanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbook': {
      id: '/_app/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AppPlaybookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prioritas': {
      id: '/_app/prioritas'
      path: '/prioritas'
      fullPath: '/prioritas'
      preLoaderRoute: typeof AppPrioritasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rencana': {
      id: '/_app/rencana'
      path: '/rencana'
      fullPath: '/rencana'
      preLoaderRoute: typeof AppRencanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ritme': {
      id: '/_app/ritme'
      path: '/ritme'
      fullPath: '/ritme'
      preLoaderRoute: typeof AppRitmeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scorecard': {
      id: '/_app/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof AppScorecardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tim': {
      id: '/_app/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof AppTimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pilar/': {
      id: '/_app/pilar/'
      path: '/pilar'
      fullPath: '/pilar/'
      preLoaderRoute: typeof AppPilarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pilar/$id': {
      id: '/_app/pilar/$id'
      path: '/pilar/$id'
      fullPath: '/pilar/$id'
      preLoaderRoute: typeof AppPilarIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiagnostikRoute: typeof AppDiagnostikRoute
  AppJurnalRoute: typeof AppJurnalRoute
  AppKeputusanRoute: typeof AppKeputusanRoute
  AppPanduanRoute: typeof AppPanduanRoute
  AppPlaybookRoute: typeof AppPlaybookRoute
  AppPrioritasRoute: typeof AppPrioritasRoute
  AppRencanaRoute: typeof AppRencanaRoute
  AppRitmeRoute: typeof AppRitmeRoute
  AppScorecardRoute: typeof AppScorecardRoute
  AppTimRoute: typeof AppTimRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPilarIdRoute: typeof AppPilarIdRoute
  AppPilarIndexRoute: typeof AppPilarIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiagnostikRoute: AppDiagnostikRoute,
  AppJurnalRoute: AppJurnalRoute,
  AppKeputusanRoute: AppKeputusanRoute,
  AppPanduanRoute: AppPanduanRoute,
  AppPlaybookRoute: AppPlaybookRoute,
  AppPrioritasRoute: AppPrioritasRoute,
  AppRencanaRoute: AppRencanaRoute,
  AppRitmeRoute: AppRitmeRoute,
  AppScorecardRoute: AppScorecardRoute,
  AppTimRoute: AppTimRoute,
  AppIndexRoute: AppIndexRoute,
  AppPilarIdRoute: AppPilarIdRoute,
  AppPilarIndexRoute: AppPilarIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
